baseURL = "https://connorcantrell.com"
title = "The Floating Pendulum"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[author]
  name = "Connor Cantrell"
abstract = "I'm a self taught software developer and an HVAC specialist located in the San Francisco Bay. A retired NASCAR driver who likes to ride motorcycles through the mountains or down the coast."

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
